Algoritmo "Exercício 2"

//Nome do(a) autor Mickael
// Data atual  : 08/08/2020
Var
// Seção de Declarações das variáveis 
N1,N2: real

Inicio
// ENTRADA DE DADOS
Escreva ( " informe um numero ")
leia (N1)
Escreva ( " informe um numero ")
leia (N2)
// PROCESSAMENTO DE DADOS
se (N1>=N2) entao
escreval (N1, " esse numero é maior que " , N2)
senao
escreval (N2, "esse numero é maior que" , N1)
//SAÍDA DE DADOS
fimse
Fimalgoritmo