Algoritmo "Exercicio 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2020
Var
// Seção de Declarações das variáveis 
Na: inteiro
Nb: inteiro

Inicio
// Entrada de dados
escreva ( " Digite um número ")
leia ( Nb )
escreva ( " Digite outro número " )
leia ( Na)

// Saída de dados
escreva ( Nb, " e ", Na )

Fimalgoritmo