Algoritmo "Exercicio 7"

// Autor(a)    : Nome do(a) aluno(a)

Var
// Seção de Declarações das variáveis 
temperaturaambiente1: inteiro

Inicio
// ENTRADA DE DADOS
escreva ( " informe a temperatura ambiente ")
leia ( temperaturaambiente1)
// PROCESSAMENTO DE DADOS
se temperaturaambiente1>=25 entao
escreval ( temperaturaambiente1, " A temperatura está muito quente! ")
senao
escreval ( temperaturaambiente1, " A temperatura está agradável!")
//SAÍDA DE DADOS
fimse
Fimalgoritmo