Algoritmo "Exercicio 12"

// Autor: Mickael
// Data atual  : 09/08/2020
Var
// Seção de Declarações das variáveis 
dias: inteiro
meses: inteiro
anos: inteiro

Inicio
// Entrada de dados
escreva ( " Anos ")
leia ( anos )
escreva ( " Meses ")
leia ( meses )
escreva ( " Dias " )
leia ( dias )
// Processamento de dados
dias <- (anos*365) + (meses*30) + dias

// Saída de dados
escreval ( " Você viveu",dias , " dias! " )

Fimalgoritmo